### ISSUE TITLE
Add Issue template for new recipes

### ISSUE THREAD

**Issue by acrosman** [SFDO-Community-Sprints/Snowfakery-Recipe-Templates#36]
To help people provide the needed information when requesting/suggesting new recipes we should create an issue template.

**Comment by RishiKumarRay** [comment]
Do you want issue template in yml?

**Comment by allisonletts** [comment]
@RishiKumarRay are you asking about the beta issue forms that github is offering? That would be great! Otherwise, we'll probably need to involve someone from SFDO to get a template added through the template builder. Even a markdown file listing the questions to ask in a new recipe request would be helpful.

Docs: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
