### ISSUE TITLE
Opportunity_npsp.recipe.yml fails when run as instructed -- Recipe needs updates

### ISSUE THREAD

**Issue by acrosman** [SFDO-Community-Sprints/Snowfakery-Recipe-Templates#92]
When run using the CCI command in the file the recipe fails with the error:
`Error: Account max ID was 3 before evaluating recipe and is 3 after. At this rate we will never hit our target!`

The command limits the recipe by Account, but the accounts are only included due to settings in the macros.

## Suggested Resolution
1. Remove macro references
2. Update recipe to included any needed elements that were loaded in those macros.
3. Test

**Comment by programmer2coder** [comment]
I started to look at this today during the Sprint.  It is weird that this YML file has both:
- include_file: ../salesforce/standard_objs.recipe.yml #this defines standard objects for reference in later sections
- include_file: standard_npsp_objs_recipe.yml #this defines simple custom objects in the NPSP architecture (referenced later)

Per guidelines, the -include will be replaced by the appropriate portion of the other file that is needed for this recipe.

Also, the recipe is in 2 parts, the first being a simple Grant Opp, and the second part being Opp (no recordtype specified) with a ton of fields that would pertain to only specific recordtypes.  The group discussion suggested breaking that out into creating ONE Opp of each of the normal recordtypes found in NPSP, with specifically the fields one would expect to see for that recordtype.  I will resume with this idea ... next time I get a chance!  Unless people @acrosman @allisonletts  have recommendations otherwise.  (If I @programmer2coder  mention myself will I get an email?  Let's see.)

**Comment by programmer2coder** [comment]
This should have closed automatically with the PR merged.
